name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.1'

      - name: Set yarn version (berry)
        run: |
          corepack enable
          yarn set version 4.1.1
      
      - name: Install packages
        run: |
          yarn install
      
      - name: Build packages
        run: |
          yarn workspaces foreach --all --topological --exclude typescript-parser run build

      - name: Test packages
        run: |
          yarn workspaces foreach --all --exclude typescript-parser run test

      - name: Authenticate with npm registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn workspaces list -v --json
          npx lerna ls --json -la
          npx lerna publish --yes --no-private --loglevel verbose
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}